---
name: 'mutation testing'
description: 'Perform mutation testing with Pitest'

inputs:
  working-directory:
    required: false
    description: 'If needed, the working directory for this action'
    default: '.'

runs:
  using: 'composite'
  steps:

    - name: 'Perform mutation testing'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn -B clean test-compile org.pitest:pitest-maven:mutationCoverage
