---
name: 'Docker push'
description: 'Push a Docker image to Docker Hub'

inputs:
  image-name:
    description: 'name of the Docker image'
    required: true
  tag-name:
    description: 'name of the tag to push'
    required: true
  dockerhub-username:
    description: 'username of Docker Hub account'
    required: true
  dockerhub-token:
    description: 'token of Docker Hub account'
    required: true
  working-directory:
    required: false
    description: 'If needed, the working directory for this action'
    default: '.'

runs:
  using: composite
  steps:

    - name: 'Login to Docker Hub'
      uses: docker/login-action@master
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: 'Push to Docker Hub'
      shell: 'bash'
      working-directory: ${{ inputs.working-directory }}
      run: |
        docker tag ${{ inputs.image-name }} ${{ inputs.image-name }}:${{ inputs.tag-name }}
        docker push ${{ inputs.image-name }}:${{ inputs.tag-name }}
