---
name: 'mutation testing'
description: 'Perform mutation testing with Pitest'

inputs:
  working-directory:
    required: false
    description: 'If needed, the working directory for this action'
    default: '.'
  java-version:
    required: false
    default: '21'
    description: 'Java version'
  java-distribution:
    required: false
    default: 'temurin'
    description: 'Java distribution'

runs:
  using: 'composite'
  steps:

    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: 'Perform mutation testing'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn -B clean test-compile org.pitest:pitest-maven:mutationCoverage
