---
name: 'Docker build'
description: 'Build a Docker image'

inputs:
  image-name:
    description: 'name of the Docker image'
    required: true

runs:
  using: composite
  steps:

    - name: 'Find build method'
      id: find-build-method
      shell: 'bash'
      run: |
        if [ -e Dockerfile ]; then
          echo "build method will be : docker"
          echo "build-method=docker" >> >> $GITHUB_OUTPUT
        elif [ -e pom.xml ]; then
          echo "build method will be : maven (with springboot)"
          echo "build-method=springboot-maven" >> >> $GITHUB_OUTPUT
        else
          echo "I don't know how to build Docker !"
        fi

    - name: 'Build Docker image with Dockerfile'
      if: ${{ steps.find-build-method.outputs.build-method == 'docker' }}
      shell: 'bash'
      run: docker build -t ${{ inputs.image-name }} .

    - name: Build Docker
      if: ${{ steps.find-build-method.outputs.build-method == 'springboot-maven' }}
      shell: 'bash'
      run: mvn -B spring-boot:build-image -Dspring-boot.build-image.imageName=${{ inputs.image-name }} -DskipTests=true
