---
name: 'Maven build'
description: 'Build a Maven project'

inputs:
  java-version:
    required: false
    default: '21'
    description: 'Java version'
  java-distribution:
    required: false
    default: 'temurin'
    description: 'Java distribution'
  artifact-path:
    required: false
    description: 'If needed, the path of the artifact to upload (wildcards allowed)'

runs:
  using: 'composite'
  steps:

    - uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        settings-path: ${{ github.workspace }}

    - name: 'Build and run unit tests'
      shell: bash
      run: mvn clean test

    - name: 'Run integration tests'
      shell: bash
      run: mvn verify
