---
name: 'Build Docker image of Maven project'

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
        description: 'Username of Docker Hub account'
      DOCKERHUB_TOKEN:
        required: true
        description: 'Token of Docker Hub account'
    inputs:
      java-version:
        required: true
        type: number
        description: 'Java version'
      java-distribution:
        required: true
        type: string
        description: 'Java distribution'
      build-method:
        required: false
        type: string
        description: 'Allow to chose Docker build method. Choice between "dockerfile" and "springboot-maven"'
      image-name:
        description: 'name of the Docker image'
        required: true
        type: string
      tag-name:
        required: true
        description: 'tag of the Docker image'
        type: string
      working-directory:
        required: false
        description: 'Working directory of the build'
        type: string
        default: '.'
      file:
        required: false
        description: |
          See "mvn -f <arg>", and description in action https://github.com/deroffal/github-actions/blob/main/actions/maven/build/action.yml.
        default: ''
        type: string
      projects:
        required: false
        description: |
          See "mvn -pl <arg>", and description in action https://github.com/deroffal/github-actions/blob/main/actions/maven/build/action.yml.
        default: ''
        type: string
jobs:
  build-maven-docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - name: 'Build with Maven'
        uses: deroffal/github-actions/actions/maven/build@main
        with:
          working-directory: ${{ inputs.working-directory }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          file: ${{ inputs.file }}
          projects: ${{ inputs.projects }}


      - name: 'Build and push Docker image'
        uses: deroffal/github-actions/actions/docker/build-and-push@main
        with:
          working-directory: ${{ inputs.working-directory }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          build-method: ${{ inputs.build-method }}
          image-name: ${{ inputs.image-name }}
          tag-name: ${{ inputs.tag-name }}

