---
name: 'CI - Maven'

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Sonarcloud token'
        required: false
    inputs:
      java-version:
        required: false
        default: '21'
        type: string
        description: 'Java version'
      java-distribution:
        required: false
        default: 'temurin'
        type: string
        description: 'Java distribution'
      artifact-path:
        required: false
        type: string
        description: 'If needed, the path of the artifact to upload (wildcards allowed)'
      working-directory:
        type: string
        description: 'Working directory of the build'
        default: '.'
        required: false
      skip-sonar:
        type: boolean
        description: 'Whether to skip Sonar analysis (true) or not (false)'
        required: false
        default: false
      skip-pit:
        type: boolean
        description: 'Whether to skip PIT mutation tests (true) or not (false)'
        required: false
        default: false
      sonar-project-key:
        type: string
        description: 'project for Sonarcloud analysis'
        required: false

jobs:
  build-project:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: 'Build with Maven'
        uses: deroffal/github-actions/actions/maven/build@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          artifact-path: ${{ inputs.artifact-path }}
          working-directory: ${{ inputs.working-directory }}

  code-analysis:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: 'Sonar analysis'
        if: ${{ inputs.skip-sonar != true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ${{ inputs.working-directory }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.sonar-project-key }}

      - name: 'Mutation tests'
        working-directory: ${{ inputs.working-directory }}
        if: ${{ inputs.skip-pit != true }}
        run: mvn -B -P pit clean verify
