---
name: 'CI - Maven'

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        default: '21'
        type: string
        description: 'Java version'
      java-distribution:
        required: false
        default: 'temurin'
        type: string
        description: 'Java distribution'
      artifact-path:
        required: false
        type: string
        description: 'If needed, the path of the artifact to upload (wildcards allowed)'
      working-directory:
        type: string
        description: 'Working directory of the build'
        default: '.'
        required: false

jobs:
  ci-maven:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Build with Maven
        uses: deroffal/github-actions/actions/maven/build@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          artifact-path: ${{ inputs.artifact-path }}
          working-directory: ${{ inputs.working-directory }}
