---
name: 'CI - Maven'

on:
  workflow_call:

jobs:
  ci-maven:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Build with Maven
        uses: deroffal/github-actions/actions/maven-build@main
