---
name: 'Continuous integration with Maven'

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Sonarcloud token'
        required: false
    inputs:
      java-version:
        required: true
        type: string
        description: 'Java version'
      java-distribution:
        required: true
        type: string
        description: 'Java distribution'
      working-directory:
        type: string
        description: 'Working directory of the build'
        default: '.'
        required: false
      sonar-project-key:
        type: string
        description: 'Project for Sonarcloud analysis (skip analysis if not provided)'
        required: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-project:
    name: "Build with Maven"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - name: 'Build with Maven'
        if: ${{ inputs.sonar-project-key == '' }}
        uses: deroffal/github-actions/actions/maven/build@main
        with:
          working-directory: ${{ inputs.working-directory }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}

      - name: 'Build with Maven & Sonar analysis'
        if: ${{ inputs.sonar-project-key != '' }}
        uses: deroffal/github-actions/actions/maven/sonar-analysis@main
        with:
          working-directory: ${{ inputs.working-directory }}
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          sonar-project-key: ${{ inputs.sonar-project-key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

